title: Karina Oborska-Balkowiec
logo: "/images/Profile.png?raw=true"
description: >
  Business-driven analyst transitioning into machine learning and data science, with 16+ years of experience in media, e-commerce, and strategic leadership. I combine a strong analytical mindset with hands-on skills in Python, SQL, data wrangling, and applied machine learning. My recent work includes a fraud detection project for a financial institution (data analysis phase), large-scale retail data modeling (Instacart), and big data processing with PySpark.

  I'm passionate about turning real-world business problems into data-driven solutions.

  👉 LinkedIn: https://www.linkedin.com/in/karina-oborska-balkowiec/  
  📂 Notion Portfolio: https://elvisliang.notion.site/Portfolio-Elvis-Liang-0d7092fc3fc34f50a878f88a380471f6?pvs=4  
  💻 GitHub Projects: *link tutaj*
theme: jekyll-theme-minimal   
  
 
